services:
  microservice:
      build: .
      ports:
        - "8080:8080"
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411'
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - ./database:/var/opt/mssql/scripts
      - sql_data:/var/opt/mssql
    ports:
      - "1433:1433"
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr &
        sleep 20 &&
        /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -i /var/opt/mssql/scripts/init.sql &&
        /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'YourStrong!Passw0rd' -i /var/opt/mssql/scripts/seed.sql
      "
volumes:
  sql_data: